import * as TE from "fp-ts/TaskEither"
import { BehaviorSubject, Observable } from "rxjs"
import { cloneDeep } from "lodash-es"
import {
  HoppRESTResponse,
  relayRequestToActualSent,
} from "./types/HoppRESTResponse"
import { EffectiveHoppRESTRequest, getComputedHeaders } from "./utils/EffectiveURL"
import { getService } from "~/modules/dioc"
import { KernelInterceptorService } from "~/services/kernel-interceptor.service"
import { RESTRequest, RESTResponse } from "~/helpers/kernel/rest"
import { RelayError } from "@hoppscotch/kernel"

export type NetworkStrategy = (
  req: EffectiveHoppRESTRequest
) => TE.TaskEither<RelayError, HoppRESTResponse>

/**
 * Classify kernelRequest.headers into system vs user headers.
 * System headers are those generated by Hoppscotch (auth + body).
 * User headers are everything else (manually added in Headers tab).
 * Since we can't rely on request.headers (UI sync bug), we identify
 * system headers via getComputedHeaders() and treat the rest as user headers.
 */
async function classifyHeaders(
  req: EffectiveHoppRESTRequest,
  kernelHeaders: Record<string, string>
): Promise<{ user: [string, string][]; system: [string, string][] }> {
  // Reconstruct pathParams + envVars to pass to getComputedHeaders
  const activePathParams = (req.pathParams ?? [])
    .filter((p) => p.key !== "" && p.active)
    .map((p) => ({
      key: p.key,
      value: p.value,
      initialValue: p.value,
      currentValue: p.value,
      secret: false as const,
    }))

  // We need the environment variables; extract from effectiveFinalHeaders
  // by comparing with the original request to recover them.
  // However, getComputedHeaders only needs the request's auth+headers,
  // so we can use the effective request directly.
  // Use empty env vars — computed headers from auth/body don't typically
  // need env resolution for KEY matching (only values), and we're matching
  // against kernelHeaders which already has resolved values.
  const envVars: { key: string; value: string; secret: boolean }[] = [
    ...activePathParams,
  ]

  const computedHeaders = await getComputedHeaders(req, envVars)

  // Build a set of system header keys (lowercased) from computed headers
  const systemHeaderKeys = new Set(
    computedHeaders
      .filter((h) => h.header.active && h.header.key !== "")
      .map((h) => h.header.key.toLowerCase())
  )

  const user: [string, string][] = []
  const system: [string, string][] = []

  for (const [key, value] of Object.entries(kernelHeaders)) {
    if (key === "") continue
    if (systemHeaderKeys.has(key.toLowerCase())) {
      system.push([key, value])
    } else {
      user.push([key, value])
    }
  }

  return { user, system }
}

export function createRESTNetworkRequestStream(
  request: EffectiveHoppRESTRequest
): [Observable<HoppRESTResponse>, () => void] {
  const response = new BehaviorSubject<HoppRESTResponse>({
    type: "loading",
    req: request,
  })

  const req = cloneDeep(request)

  const execResult = RESTRequest.toRequest(req).then(async (kernelRequest) => {
    if (!kernelRequest) {
      response.next({
        type: "network_fail",
        req,
        error: new Error("Failed to create kernel request"),
      })
      response.complete()
      return null
    }

    // Classify headers by comparing kernel headers with computed system headers
    const { user: userHeaders, system: systemHeaders } = await classifyHeaders(
      req,
      kernelRequest.headers
    )
    const actualSent = relayRequestToActualSent(
      kernelRequest,
      userHeaders,
      systemHeaders
    )

    const result = service.execute(kernelRequest)

    result.response.then(async (res) => {
      if (res._tag === "Right") {
        const processedRes = await RESTResponse.toResponse(res.right, req)

        if (processedRes.type === "success") {
          // Attach the actual sent request data to the response
          response.next({
            ...processedRes,
            actualSentRequest: actualSent,
          })
        } else {
          // For transform_error responses, also attach actual sent request
          response.next({
            type: "network_fail",
            req,
            error: processedRes.error,
          })
        }
      } else {
        response.next({
          type: "interceptor_error",
          req,
          error: res.left,
        })
      }
      response.complete()
    })

    return result
  })

  const service = getService(KernelInterceptorService)

  return [
    response,
    async () => {
      try {
        const result = await execResult
        if (result) await result.cancel()
      } catch (_error) {
        // Ignore cancel errors - request may have already completed
        // This is expected behavior and not an actual error
      }
    },
  ]
}
